Mon, 06 Sep 2021 15:57:26 main.py[line:166] INFO Execute Swagger API testing now: 2021-09-06 15:57:26, please wait for a moment: 
Mon, 06 Sep 2021 15:57:26 main.py[line:172] INFO prepare to create folder to save test scripts: ./TestSuites
Mon, 06 Sep 2021 15:57:26 main.py[line:122] INFO The swagger api_docs url is https://petstore.swagger.io/v2/swagger.json, the output testcase csv file is ./TestResult/testcases.csv, the html report file is ./TestResult/result.html
Mon, 06 Sep 2021 15:57:26 main.py[line:123] INFO request swagger url: https://petstore.swagger.io/v2/swagger.json to get all api-docs content
Mon, 06 Sep 2021 15:57:56 connectionpool.py[line:781] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd5a13747b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v2/swagger.json
Mon, 06 Sep 2021 15:58:26 connectionpool.py[line:781] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd5a13748d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v2/swagger.json
Mon, 06 Sep 2021 15:58:56 connectionpool.py[line:781] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd5a13749b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /v2/swagger.json
Mon, 06 Sep 2021 15:59:26 main.py[line:127] ERROR swagger url: https://petstore.swagger.io/v2/swagger.json access fail, exception info: MaxRetryError("HTTPSConnectionPool(host='petstore.swagger.io', port=443): Max retries exceeded with url: /v2/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd5a1374a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",)
